runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "latest"
- name: MySQLdb
  version: "latest"

env_variables:
  CLOUDSQL_CONNECTION_NAME: caredb
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: sqlbernie51

